version: '3.8'

services:
  sendgrid-logger:
    build:
      context: ./SendgridParquetLogger
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - S3__AccessKey=${S3__AccessKey}
      - S3__SecretKey=${S3__SecretKey}
      - S3__ServiceUrl=${S3__ServiceUrl}
      - S3__BucketName=${S3__BucketName}
    restart: unless-stopped