@SendgridParquetLogger_HostAddress = http://localhost:5206

###
# health
GET {{SendgridParquetLogger_HostAddress}}/health6QQl

###
# Sendgrid WebHook Event (2025-09 timestamp sample)
# Sendgrid WebHook Event (2024-02-29 timestamp sample)　search 1709194530
POST {{SendgridParquetLogger_HostAddress}}/webhook/sendgrid
Content-Type: application/json

[
  {
    "email": "example@example.com",
    "timestamp": 1757939696,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757939696",
    "event": "processed",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757939696",
    "sg_message_id": "sg_message_id_1757939696"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757939756,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757939756",
    "event": "deferred",
    "ip": "168.1.1.1",
    "category": [
      "cat facts",
      "dog facts"
    ],
    "unique_args": {
      "order_id": "12345",
      "campaign": "summer_sale"
    },
    "sg_event_id": "sg_event_id_1757939756",
    "sg_message_id": "sg_message_id_1757939756",
    "response": "400 try again later",
    "attempt": "5"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757939816,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757939816",
    "event": "delivered",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757939816",
    "sg_message_id": "sg_message_id_1757939816",
    "response": "250 OK"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757939876,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757939876",
    "event": "open",
    "sg_machine_open": false,
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757939876",
    "sg_message_id": "sg_message_id_1757939876",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757939936,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757939936",
    "event": "click",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757939936",
    "sg_message_id": "sg_message_id_1757939936",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255",
    "url": "http://www.sendgrid.com/"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757939996,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757939996",
    "bounce_classification": "Invalid Address",
    "event": "bounce",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757939996",
    "sg_message_id": "sg_message_id_1757939996",
    "reason": "500 unknown recipient",
    "status": "5.0.0"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940056,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940056",
    "event": "dropped",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940056",
    "sg_message_id": "sg_message_id_1757940056",
    "reason": "Bounced Address",
    "status": "5.0.0"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940116,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940116",
    "event": "spamreport",
    "sg_event_id": "sg_event_id_1757940116",
    "sg_message_id": "sg_message_id_1757940116"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940176,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940176",
    "event": "unsubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940176",
    "sg_message_id": "sg_message_id_1757940176"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940236,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940236",
    "event": "group_unsubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940236",
    "sg_message_id": "sg_message_id_1757940236",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255",
    "url": "http://www.sendgrid.com/",
    "asm_group_id": 10
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940296,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940296",
    "event": "group_resubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940296",
    "sg_message_id": "sg_message_id_1757940296",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "000.000.000.000",
    "url": "http://www.sendgrid.com/",
    "asm_group_id": 10
  },
  {
    "event": "account_status_change",
    "sg_event_id": "MjEzNTg5OTcyOC10ZXJtaW5hdGUtMTcwNzg1MTUzMQ_1757940356",
    "timestamp": 1757940356,
    "type": "compliance_suspend"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940416,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940416",
    "event": "processed",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940416",
    "sg_message_id": "sg_message_id_1757940416"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940476,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940476",
    "event": "deferred",
    "ip": "168.1.1.1",
    "category": [
      "cat facts",
      "dog facts"
    ],
    "unique_args": {
      "order_id": "12345",
      "campaign": "summer_sale"
    },
    "sg_event_id": "sg_event_id_1757940476",
    "sg_message_id": "sg_message_id_1757940476",
    "response": "400 try again later",
    "attempt": "5"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940536,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940536",
    "event": "delivered",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940536",
    "sg_message_id": "sg_message_id_1757940536",
    "response": "250 OK"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940596,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940596",
    "event": "open",
    "sg_machine_open": false,
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940596",
    "sg_message_id": "sg_message_id_1757940596",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940656,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940656",
    "event": "click",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940656",
    "sg_message_id": "sg_message_id_1757940656",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255",
    "url": "http://www.sendgrid.com/"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940716,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940716",
    "bounce_classification": "Invalid Address",
    "event": "bounce",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940716",
    "sg_message_id": "sg_message_id_1757940716",
    "reason": "500 unknown recipient",
    "status": "5.0.0"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940776,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940776",
    "event": "dropped",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940776",
    "sg_message_id": "sg_message_id_1757940776",
    "reason": "Bounced Address",
    "status": "5.0.0"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940836,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940836",
    "event": "spamreport",
    "sg_event_id": "sg_event_id_1757940836",
    "sg_message_id": "sg_message_id_1757940836"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940896,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940896",
    "event": "unsubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940896",
    "sg_message_id": "sg_message_id_1757940896"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757940956,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757940956",
    "event": "group_unsubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757940956",
    "sg_message_id": "sg_message_id_1757940956",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255",
    "url": "http://www.sendgrid.com/",
    "asm_group_id": 10
  },
  {
    "email": "example@example.com",
    "timestamp": 1757941016,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757941016",
    "event": "group_resubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1757941016",
    "sg_message_id": "sg_message_id_1757941016",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "000.000.000.000",
    "url": "http://www.sendgrid.com/",
    "asm_group_id": 10
  },
  {
    "event": "account_status_change",
    "sg_event_id": "MjEzNTg5OTcyOC10ZXJtaW5hdGUtMTcwNzg1MTUzMQ_1757941076",
    "timestamp": 1757941076,
    "type": "compliance_suspend"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757941136,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757941136",
    "event": "processed",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_202402290800_1757941136",
    "sg_message_id": "sg_message_id_202402290800_1757941136"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757941196,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757941196",
    "event": "processed",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_202402291300_1757941196",
    "sg_message_id": "sg_message_id_202402291300_1757941196"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757941256,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757941256",
    "event": "processed",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_202403010800_1757941256",
    "sg_message_id": "sg_message_id_202403010800_1757941256"
  },
  {
    "email": "example@example.com",
    "timestamp": 1757941316,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1757941316",
    "event": "processed",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_202403011300_1757941316",
    "sg_message_id": "sg_message_id_202403011300_1757941316"
  },
  {
    "email": "example@example.com",
    "timestamp": 1709194530,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709194530",
    "event": "processed",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1709194530",
    "sg_message_id": "sg_message_id_1709194530"
  },
  {
    "email": "example@example.com",
    "timestamp": 1709194590,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709194590",
    "event": "deferred",
    "ip": "168.1.1.1",
    "category": [
      "cat facts",
      "dog facts"
    ],
    "unique_args": {
      "order_id": "12345",
      "campaign": "summer_sale"
    },
    "sg_event_id": "sg_event_id_1709194590",
    "sg_message_id": "sg_message_id_1709194590",
    "response": "400 try again later",
    "attempt": "5"
  },
  {
    "email": "example@example.com",
    "timestamp": 1709194650,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709194650",
    "event": "delivered",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1709194650",
    "sg_message_id": "sg_message_id_1709194650",
    "response": "250 OK"
  },
  {
    "email": "example@example.com",
    "timestamp": 1709194710,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709194710",
    "event": "open",
    "sg_machine_open": false,
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1709194710",
    "sg_message_id": "sg_message_id_1709194710",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255"
  },
  {
    "email": "example@example.com",
    "timestamp": 1709194770,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709194770",
    "event": "click",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1709194770",
    "sg_message_id": "sg_message_id_1709194770",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255",
    "url": "http://www.sendgrid.com/"
  },
  {
    "email": "example@example.com",
    "timestamp": 1709194830,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709194830",
    "bounce_classification": "Invalid Address",
    "event": "bounce",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1709194830",
    "sg_message_id": "sg_message_id_1709194830",
    "reason": "500 unknown recipient",
    "status": "5.0.0"
  },
  {
    "email": "example@example.com",
    "timestamp": 1709194890,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709194890",
    "event": "dropped",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1709194890",
    "sg_message_id": "sg_message_id_1709194890",
    "reason": "Bounced Address",
    "status": "5.0.0"
  },
  {
    "email": "example@example.com",
    "timestamp": 1709194950,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709194950",
    "event": "spamreport",
    "sg_event_id": "sg_event_id_1709194950",
    "sg_message_id": "sg_message_id_1709194950"
  },
  {
    "email": "example@example.com",
    "timestamp": 1709195010,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709195010",
    "event": "unsubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1709195010",
    "sg_message_id": "sg_message_id_1709195010"
  },
  {
    "email": "example@example.com",
    "timestamp": 1709195070,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709195070",
    "event": "group_unsubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1709195070",
    "sg_message_id": "sg_message_id_1709195070",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255",
    "url": "http://www.sendgrid.com/",
    "asm_group_id": 10
  },
  {
    "email": "example@example.com",
    "timestamp": 1709195130,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1709195130",
    "event": "group_resubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1709195130",
    "sg_message_id": "sg_message_id_1709195130",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "000.000.000.000",
    "url": "http://www.sendgrid.com/",
    "asm_group_id": 10
  },
  {
    "event": "account_status_change",
    "sg_event_id": "MjEzNTg5OTcyOC10ZXJtaW5hdGUtMTcwNzg1MTUzMQ_1709195190",
    "timestamp": 1709195190,
    "type": "compliance_suspend"
  }
]

###
# Sendgrid WebHook Event
POST {{SendgridParquetLogger_HostAddress}}/webhook/sendgrid
Content-Type: application/json

[
  {
    "email": "example@example.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513299569",
    "event": "processed",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1513299569",
    "sg_message_id": "sg_message_id_1513299569"
  },
  {
    "email": "example@example.com",
    "timestamp": 1513299629,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513299629",
    "event": "deferred",
    "ip": "168.1.1.1",
    "category": [
      "cat facts",
      "dog facts"
    ],
    "unique_args": {
      "order_id": "12345",
      "campaign": "summer_sale"
    },
    "sg_event_id": "sg_event_id_1513299629",
    "sg_message_id": "sg_message_id_1513299629",
    "response": "400 try again later",
    "attempt": "5"
  },
  {
    "email": "example@example.com",
    "timestamp": 1513299689,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513299689",
    "event": "delivered",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1513299689",
    "sg_message_id": "sg_message_id_1513299689",
    "response": "250 OK"
  },
  {
    "email": "example@example.com",
    "timestamp": 1513299749,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513299749",
    "event": "open",
    "sg_machine_open": false,
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1513299749",
    "sg_message_id": "sg_message_id_1513299749",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255"
  },
  {
    "email": "example@example.com",
    "timestamp": 1513299809,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513299809",
    "event": "click",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1513299809",
    "sg_message_id": "sg_message_id_1513299809",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255",
    "url": "http://www.sendgrid.com/"
  },
  {
    "email": "example@example.com",
    "timestamp": 1513299869,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513299869",
    "bounce_classification": "Invalid Address",
    "event": "bounce",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1513299869",
    "sg_message_id": "sg_message_id_1513299869",
    "reason": "500 unknown recipient",
    "status": "5.0.0"
  },
  {
    "email": "example@example.com",
    "timestamp": 1513299929,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513299929",
    "event": "dropped",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1513299929",
    "sg_message_id": "sg_message_id_1513299929",
    "reason": "Bounced Address",
    "status": "5.0.0"
  },
  {
    "email": "example@example.com",
    "timestamp": 1513299989,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513299989",
    "event": "spamreport",
    "sg_event_id": "sg_event_id_1513299989",
    "sg_message_id": "sg_message_id_1513299989"
  },
  {
    "email": "example@example.com",
    "timestamp": 1513300049,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513300049",
    "event": "unsubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1513300049",
    "sg_message_id": "sg_message_id_1513300049"
  },
  {
    "email": "example@example.com",
    "timestamp": 1513300109,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513300109",
    "event": "group_unsubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1513300109",
    "sg_message_id": "sg_message_id_1513300109",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255",
    "url": "http://www.sendgrid.com/",
    "asm_group_id": 10
  },
  {
    "email": "example@example.com",
    "timestamp": 1513300169,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>_1513300169",
    "event": "group_resubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id_1513300169",
    "sg_message_id": "sg_message_id_1513300169",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "000.000.000.000",
    "url": "http://www.sendgrid.com/",
    "asm_group_id": 10
  },
  {
    "event": "account_status_change",
    "sg_event_id": "MjEzNTg5OTcyOC10ZXJtaW5hdGUtMTcwNzg1MTUzMQ_1513300229",
    "timestamp": 1513300229,
    "type": "compliance_suspend"
  }
]
