name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Generate version from date and commit SHA
  VERSION: ${{ github.run_number }}-${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_URL }}
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.CONTAINER_REGISTRY_URL }}/sendgridparquetlog-sendgrid-logger
          tags: |
            type=raw,value=run_number${{ github.run_number }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./SendgridParquetLogger/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: Set Docker image URL for deployment
        run: |
          echo "DOCKER_FULL_IMAGE_URL=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV

      - name: Deploy to Sakura Cloud
        env:
          SAKURACLOUD_ACCESS_TOKEN: ${{ vars.SAKURACLOUD_ACCESS_TOKEN }}
          SAKURACLOUD_ACCESS_TOKEN_SECRET: ${{ secrets.SAKURACLOUD_ACCESS_TOKEN_SECRET }}
          S3__SERVICEURL: ${{ vars.S3__SERVICEURL }}
          S3__REGION: ${{ vars.S3__REGION }}
          S3__ACCESSKEY: ${{ vars.S3__ACCESSKEY }}
          S3__SECRETKEY: ${{ secrets.S3__SECRETKEY }}
          S3__BUCKETNAME: ${{ vars.S3__BUCKETNAME }}
          APP_NAME: "sendgridparquetlog-sendgrid-logger"
          APPRUN_PORT: "8080"
          APPRUN_TIMEOUT: "180"
        run: |
          echo "Deploying image: ${DOCKER_FULL_IMAGE_URL}"
          bash ./Deploy/SakuraCloud.sh \
            "${APP_NAME}" \
            "${APPRUN_PORT}" \
            "${DOCKER_FULL_IMAGE_URL}"
