name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Generate version from date and commit SHA
  VERSION: ${{ github.run_number }}-${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_URL }}
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build with docker compose
        run: |
          docker compose build

      - name: Deploy to Sakura Cloud
        env:
          SAKURACLOUD_ACCESS_TOKEN: ${{ vars.SAKURACLOUD_ACCESS_TOKEN }}
          SAKURACLOUD_ACCESS_TOKEN_SECRET: ${{ secrets.SAKURACLOUD_ACCESS_TOKEN_SECRET }}
          CONTAINER_REGISTRY_URL: ${{ vars.CONTAINER_REGISTRY_URL }}
          CONTAINER_REGISTRY_USERNAME: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          S3__ServiceUrl: ${{ vars.S3__ServiceUrl }}
          S3__AccessKey: ${{ vars.S3__AccessKey }}
          S3__SecretKey: ${{ secrets.S3__SecretKey }}
          S3__BucketName: ${{ vars.S3__BucketName }}
        run: |
          # Application name (must match docker compose service name)
          APP_NAME="sendgridparquetlog-sendgrid-logger"
          APPRUN_PORT=8080
          
          echo "Deploying version: run_number${GITHUB_RUN_NUMBER}"
          
          # Make script executable
          chmod +x ./Deploy/SakuraCloud.sh
          
          # Call SakuraCloud.sh with app name, port, and version tag
          bash ./Deploy/SakuraCloud.sh \
            "${APP_NAME}" \
            "${APPRUN_PORT}" \
            "run_number${GITHUB_RUN_NUMBER}"
